# The is the default codecov.io yaml configuration all projects use
# that do not have their own codecov.yml already in the project.
#
# https://docs.codecov.io/docs/codecov-yaml#section-default-yaml

# This section provides the generic configuration for codecov.
#
# https://docs.codecov.io/docs/codecovyml-reference#section-codecov
codecov:

  require_ci_to_pass: yes

# This section provides the configuration for the
# coverage report codecov analyzes for results.
#
# https://docs.codecov.io/docs/codecovyml-reference#section-coverage
coverage:

  precision: 2
  round: down
  range: "70...100"

  # https://docs.codecov.io/docs/commit-status
  status:
    # set rules for the project status report
    project:
      default:
        target: 90%
        threshold: 0%
    # disable the patch status report
    patch: off
    # disable the changes status report
    changes: off

# This section provides the configuration for the
# parsers codecov uses for the coverage report.
#
# https://docs.codecov.io/docs/codecovyml-reference#section-parsers
parsers:

  gcov:

    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# This section provides the configuration for the
# comments codecov makes to open pull requests.
#
# https://docs.codecov.io/docs/codecovyml-reference#section-comment
comment:

  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

# This section tells codecov to ignore certain paths
# that match this list of path globs.
#
# https://docs.codecov.com/docs/codecovyml-reference#ignore
ignore:
  # ignore all but client.go and exec.go
  - "cmd/vela-worker/flags.go"
  - "cmd/vela-worker/main.go"
  - "cmd/vela-worker/operate.go"
  - "cmd/vela-worker/r*.go"
  - "cmd/vela-worker/s*.go"
  - "cmd/vela-worker/validate.go"
  - "cmd/vela-worker/worker.go"
