scrape_configs:
  - job_name: 'worker build usage'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.8:8081']
    scrape_interval: 1s
  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'localhost:9090' ]