on: 
  pull_request:
  push:
    branches: 
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    name: Validate/Test
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: clone
      uses: actions/checkout@v1      
    - name: validate
      run: |
        # Check that go mod tidy produces a zero diff; clean up any changes afterwards.
        go mod tidy && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go vet ./... produces a zero diff; clean up any changes afterwards.
        go vet ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 
        # Check that go fmt ./... produces a zero diff; clean up any changes afterwards.
        go fmt ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 
    - name: test
      run: go test -cover ./...
