name: Release Action
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:

    - name: clone
      uses: actions/checkout@master

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: go build -a -ldflags '-s -w -extldflags "-static"' -o release/vela-worker github.com/go-vela/worker/cmd/server

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-worker
        cache: true
        tag_names: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
